### ISSUE TITLE
Asyncio support?

### ISSUE THREAD

**Issue by maxifom** [jdepoix/youtube-transcript-api#122]

**Comment by jdepoix** [comment]
What kind of support are you looking for, can't you simply wrap calls to this module in async functions?

**Comment by maxifom** [comment]
I want aiohttp implementation. Indeed I can wrap it in PoolExecutors to not block async executions, but its not the best way in async Python

**Comment by jdepoix** [comment]
I don't plan to support http clients other than requests as of now. However, feel free to open a PR if you think this would be a valuable addition and I would be open to merge it if the implementation isn't too invasive.
My concern is that you won't really benefit from doing multiple async requests concurrently as this just increases your changes of getting IP blocked by YouTube, due to the high amount of requests.
