### ISSUE TITLE
TranscriptsDisabled exception

### ISSUE THREAD

**Issue by dankeinan1** [jdepoix/youtube-transcript-api#128]
Hi,
I am trying to use this API to get the manually created transcript in Hebrew of YouTube videos.
I am using these code:
`transcript_list = YouTubeTranscriptApi.list_transcripts([video_id])
transcript = transcript_list.find_manually_created_transcript(['he'])`

I tried it with many different videos with manually created captions, one video for example: https://www.youtube.com/watch?v=i5_5gGimcio
I also tried 'iw' for the language code.

I keep getting the TranscriptsDisabled exception.
What am I doing wrong?

**Comment by jdepoix** [comment]
Hi @dankeinan1, `list_transcripts()` should receive a single video id instead of a list of video ids. The name is pluralized because it returns multiple transcripts not because it takes multiple inputs 😊 
I realise that a lot of people get confused with input types, that why I am planning to add type assertions in #125.
I will close this for now, let me know if you're still having issues.
