### ISSUE TITLE
How do you get around the captcha?

### ISSUE THREAD

**Issue by crysfel** [jdepoix/youtube-transcript-api#141]
Hi there! Awesome project you have here!

I have a question, how do you get around the captcha? I'm opening youtube from a PHP script I have, it works pretty good on my local, but when I tried on my production server I'm getting this error:

```
Our systems have detected unusual traffic from your computer network.  This page checks to see if it&#39;s really you sending the requests, and not a robot.  <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Why did this happen?</a><br><be>
```

I installed this package on my production server and did a quick test, it works pretty well! I looked at the code and it's basically [a call to youtube website](https://github.com/jdepoix/youtube-transcript-api/blob/master/youtube_transcript_api/_transcripts.py#L88).

But, how do you do to avoid getting the captcha?

Regards!

**Comment by jdepoix** [comment]
Hi @crysfel,

unfortunately, there isn't really an easy way to work around captchas, since blocking traffic from bots pretty much is the point of captchas 😄 

The only thing you can do to work around YouTube blocking you is to change your IP address in any way (like using proxies), or simply waiting until they have lifted the ban (I don't know how long you'll have to wait though, as it seems to be fairly inconsistent).

I will close this issue, as there unfortunately isn't much we can do here.
