### ISSUE TITLE
Transcripts present in youtube but api is throwing error

### ISSUE THREAD

**Issue by soumyasj** [jdepoix/youtube-transcript-api#147]
For the following video link
https://www.youtube.com/watch?v=4F2N1QUI7hc
Transcripts are present in youtube but the api throws the following error
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=4F2N1QUI7hc! This is most likely caused by:

Subtitles are disabled for this video

**Comment by jdepoix** [comment]
When I open that YouTube link it gives me an error that this video is not allowed to viewed from my country (Germany). Therefore I can't really check what's going on. But it seems very likely to me that this is the reason for your error. Since requests done by this module are not authenticated, videos which are restricted to certain countries probably won't work. However, you could try and use a cookie from a logged in session. [Check out the docs to find out how to that](https://github.com/jdepoix/youtube-transcript-api#cookies).

Please let me know if that fixed the issue, so that I know for future issues!

**Comment by jdepoix** [comment]
@soumyasj have you had the chance to try it using an existing session? Can I close this issue?

**Comment by rob70** [comment]
I ran into a similar issue for 0.4.4  for this video:
https://www.youtube.com/watch?v=TJqlmb1FPyI
The subtitles show up in my browser, and translation works, too.
The youtube channel owner says he has experienced an issue with the subtitles, however: 
https://twitter.com/JabbarRafique/status/1510022079135027200.
It is not an age-restricted video and does not require a login to watch. 
Thanks.

**Comment by jdepoix** [comment]
@rob70 have you specified the language? Only russian subtitles are available and if no language is specified english will be used as the default. Therefore, no transcript is found. I can retrieve the transcripts without a problem when running:
```python
YouTubeTranscriptApi.get_transcript("TJqlmb1FPyI", ["ru"])
```

**Comment by rob70** [comment]
Thanks for swift response. This worked out for me as well.

**Comment by jdepoix** [comment]
I will close this now due to inactivity

**Comment by soumyasj** [comment]
Greetings,
You can close the issue. Thank you.

*Regards,Soumya Shamarao JahagirdarMasters' by Research (MS), CVIT, IIIT
Hyderabad*
