### ISSUE TITLE
Transcriptions of shorts videos are outsync

### ISSUE THREAD

**Issue by titusfx** [jdepoix/youtube-transcript-api#163]
I'm being using a script for getting transcript working 100% until today, that I tried to download a short. The time was quite off.

https://www.youtube.com/watch?v=uCbpDW0p0Gs

Thanks

**Comment by jdepoix** [comment]
Hi @titusfx,
could you please clarify what exactly is not working for you? I can't find anything wrong with the video you posted using the current version of `youtube-transcript-api`.

**Comment by jdepoix** [comment]
Any news on this @titusfx? Otherwise I will close this issue.

**Comment by titusfx** [comment]
Hi @jdepoix the same link is https://www.youtube.com/shorts/uCbpDW0p0Gs as you can see the format is different, and in order to work I need to manually do: 

1. Convert this format to the other (from https://www.youtube.com/shorts/uCbpDW0p0Gs to https://www.youtube.com/watch?v=uCbpDW0p0Gs)
2. Watch a part of the video (open the link, only it won't work)
3. And then the video transcriptions/translation are available on the library

So, you need to find a short video that wasn't opened with the equivalent link.

I'm using the last version of `youtube-transcript-api`

**Comment by jdepoix** [comment]
Hi @titusfx,
I have no experience with getting transcripts for shorts and since shorts aren't really supported by this module yet, this sounds more like a feature request than a bug. What you are describing seems to indicate that YouTube generates the transcript lazily only after the video has been opened using a `https://www.youtube.com/watch....` url. In that case there is no way for this module to work around that. But you could write some code to call the watch url first and then wait until the transcript is available.
