### ISSUE TITLE
Does not detect variants of English subtitle like English-India, English-UK, etc.

### ISSUE THREAD

**Issue by sshenoy03** [jdepoix/youtube-transcript-api#197]
# To Reproduce
https://youtu.be/WngejdXGvnU
Try running the api on this video , its subtitles are in English-India , it wont work properly

### What code / cli command are you executing?

# Expected behavior
Should have displayed the transcript just like ordinary English subtitle but fails to do so 

# Actual behaviour
Declares  subtitle not available

**Comment by jdepoix** [comment]
I am not sure what you are executing, since you didn't provide any code or error messages. Therefore, I can only assume that you are trying to retrieve the transcript without specifying which language you want. The default is `en`, however, English-India is `en-IN`, so the module is correct in saying that there is no English subtitle.

You have to run `youtube_transcript_api WngejdXGvnU --languages en-IN` or `YouTubeTranscriptApi.get_transcript("WngejdXGvnU", languages=["en-IN"])`
