### ISSUE TITLE
is there any way to probe/list available transcripts?

### ISSUE THREAD

**Issue by 96fps** [jdepoix/youtube-transcript-api#22]
for a given video, could there be a way to list all the available  transcripts (short of manually trying/failing a series of language codes)? Either to fetch them all at once or as a way to inform what can be fetched

Some videos have transcripts in 20+ languages (say this one https://www.youtube.com/watch?v=GAgp7nXdkLU), or just have multiple english transcripts (auto/manually generated) and I'd be useful to collect/compare them.

Thanks for making this tool

**Comment by 96fps** [comment]
I had a skim of the youtube API and it looks like the ïntended" way they expose it requires the use of an API key, which may or may not be beyond the scope of your tool.  https://developers.google.com/youtube/v3/docs/captions/list#usage

**Comment by jdepoix** [comment]
Hi @96fps,

as of know I don't know of a way to find out which subtitles are available, without using the Captions API. However, I am sure that there is a way to get them without having an API Key scraping the frontend, as the list of subtitles is available in the frontend, even when you are not logged in. Unfortunately I am currently a bit limited on time, but if you wanna do some research on how to get available transcripts I could probably implement it without too much effort! 😃

But I definitely don't want to integrate Captions API into this module. I think if you need the functionality of Captions API while also wanting to retrieve automatically generated subtitles, you are perfectly fine to use Captions API and youtube-transcript-api in conjunction.
However, I agree that in that case it could turn out to be a problem that you can't differentiate between automatically and manually generated subtitles as of now. But I recently found out that only automatically generated subtitles are retrieved when `kind=asr` is added to the request, however I haven't implemented this into this module yet. The current behaviour is that manually generated subtitles are retrieved if there are any and automatically generated subtitles otherwise, which probably is favorable for most usecases (but not yours...). I will look into adding a flag to the `get_transcript` call, which will make it only retrieve automatically generated subtitles. Would this help solve your problem?

**Comment by 96fps** [comment]
That would certainly be helpful, even if it doesn't 100% solve my problem.

It does look like `youtube-dl` has a `--list-subs` option, which helps, and it even distinguishes between manually created subtitles and automatically generated ones, (although the latter appears to conflate both automatically transcribed subtitles from the audio with automatically translated subtitles)

**Comment by jdepoix** [comment]
Hi @96fps,
I am happy to tell you that the feature you are asking for has been implemented as of v0.2.0! Closing this Issue now.
