### ISSUE TITLE
'TranscriptsDisabled' for videos with available subtitles

### ISSUE THREAD

**Issue by Tomtunn** [jdepoix/youtube-transcript-api#301]
To Reproduce 
I'm encountering the `TranscriptsDisabled `error when using youtube_transcript_api to fetch transcripts for videos where subtitles are enable on video. This has been observed specifically with Thai language videos, but it's unclear if it's language-specific or a more general issue.
<img src="https://github.com/user-attachments/assets/240868f7-4e13-4be4-9c5c-f5d44ef82a05" width=500 height=300>

I am running
```
from youtube_transcript_api import YouTubeTranscriptApi
link = "https://www.youtube.com/watch?v=2qVB2pljIeo" # thai language
video_id = link.split("v=")[1]
transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
```

youtube link https://www.youtube.com/watch?v=2qVB2pljIeo
video_id "2qVB2pljIeo"
Python 3.12.4
youtube-transcript-api 0.6.2

The error message:
```
TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=2qVB2pljIeo! This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by Tide44-cmd** [comment]
I recently ran into a similar issue today for
https://www.youtube.com/watch?v=sPAE0cr5eno
both subtitles and transcript are available on the video in English
![image](https://github.com/user-attachments/assets/233ce0ab-aab6-4186-bb64-7e4fec4549f8)

![image](https://github.com/user-attachments/assets/cca998bc-402c-419b-a355-c95252748f26)

error from API

TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=LH-sPAE0cr5eno! This is most likely caused by:

Subtitles are disabled for this video

![image](https://github.com/user-attachments/assets/233ce0ab-aab6-4186-bb64-7e4fec4549f8)

**Comment by jdepoix** [comment]
Hi @Tide44-cmd,
there probably is a bug in the code that's parsing out the video ID. The URL in the error message shows that the ID being used is `LH-sPAE0cr5eno`, while it should be `LH-sPAE0cr5eno`. If I run it with `sPAE0cr5eno` I can retrieve the transcripts without a problem.
So I don't think that your issue is related.

**Comment by Tomtunn** [comment]
Thanks, @jdepoix. That just works. I found out that the subtitle is available only for YouTube premium members, so adding a cookie parameter helps solve the issue.
