### ISSUE TITLE
YouTubeTranscriptApi class fails in production environment

### ISSUE THREAD

**Issue by yevgetman** [jdepoix/youtube-transcript-api#309]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce

Go to [https://www.ysummary.com/](https://www.ysummary.com/), enter any YouTube video URL into the input field, and click "Summarize".

### What code / cli command are you executing?

**YouTubeTranscriptApi.get_transcript(video_id)**

### Which Python version are you using?
Python **3.12.4**

### Which version of youtube-transcript-api are you using?
youtube-transcript-api **0.6.2**

# Expected behavior

The application should return an AI-generated summary of the YouTube video transcript. 

# Actual behaviour

The application returns an error message.  

```
Could not retrieve a transcript for the video. This is most likely caused by:

Subtitles are disabled for this video

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

I am 100% sure that the described cause is not responsible for this error. The video submitted as input does in fact have subtitles enabled and a transcript available.

I have tested this locally using the exact same code and video and the application works successfully. It only fails when running in production. 

Moreover, this application worked successfully in production for about a weeks time before it started returning this error for every input. 

I have tested this using a number of proxies, library versions, and other attempts to resolve but have been unsuccessfull so far.

**Comment by Joe-hitthecode** [comment]
I am experiencing similar problem. I have been running the library in production for months now. It works fine locally but it is failing in production with the same error message: 

    transcript_data = YouTubeTranscriptApi.list_transcripts(video_id)
  File "/home/joeslamie/.virtualenvs/myenv/lib/python3.10/site-packages/youtube_transcript_api/_api.py", line 71, in list_transcripts
    return TranscriptListFetcher(http_client).fetch(video_id)
  File "/home/joeslamie/.virtualenvs/myenv/lib/python3.10/site-packages/youtube_transcript_api/_transcripts.py", line 48, in fetch
    self._extract_captions_json(self._fetch_video_html(video_id), video_id),
  File "/home/joeslamie/.virtualenvs/myenv/lib/python3.10/site-packages/youtube_transcript_api/_transcripts.py", line 62, in _extract_captions_json
    raise TranscriptsDisabled(video_id)
youtube_transcript_api._errors.TranscriptsDisabled: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=P7Hkh2zOGQ0! This is most likely caused by:
**NO MATCH**
Subtitles are disabled for this video
**NO MATCH**
If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

**Comment by yxw2014** [comment]
I have the same problem! 😭

**Comment by tiagofonsecacosta** [comment]
Oops, me too :/ Any known solutions?

**Comment by meera** [comment]
Same problem!!
