### ISSUE TITLE
Transcripts Unavailable for All Videos

### ISSUE THREAD

**Issue by kskip001** [jdepoix/youtube-transcript-api#358]
DO NOT DELETE THIS! Please take the time to fill this out properly. I am not able to help you if I do not know what you are executing and what error messages you are getting. If you are having problems with a specific video make sure to **include the video id**.

# To Reproduce
Search for transcript using VideoID. (This error happens regardless of VideoID - I've tried quite a few and keep having the issue)

### What code / cli command are you executing?
I am running a JS script to fetch transcripts and store on a database.
```
YouTubeTranscriptApi.get_transcript(video_id)
```

### Which Python version are you using?
Python 3.10.7

### Which version of youtube-transcript-api are you using?
youtube-transcript-api 0.6.3

# Expected behavior
Describe what you expected to happen. 

I used this tool earlier today and it was working fine. I expected to receive a transcript as usual and I wanted to check if other people were having the same issue as me.

# Actual behaviour
I received the following error message:
```
# .Transcript unavailable: No transcript available: Could not retrieve a transcript for the video https://www.youtube.com/watch?v=xdshPqDSHBE! This is most likely caused by: Subtitles are disabled for this video If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!
```

**Comment by kskip001** [comment]
Apologies @jdepoix  and thanks for the quick response. I checked #303 and it looks like it in fact was a blacklist issue. Switching IPs seems to have worked.

I wonder if we could come to some sort of standard for rate limiting to help avoid this. Thanks again for the library and quick support :)

**Comment by jdepoix** [comment]
Hi @kskip001, from what people have been reporting there seems to be no consistency on when YouTube blocks/unblocks IPs, so I can't give any guidance on that. Also, the problem is especially prevalent when this module is used in the Cloud, since the IP of whatever instance you are running your code on might be shared with others (depending on your setup). So in this case there is not way of knowing how many requests have already been done with the IP you are using. It could also be that YouTube just generally blocks some IP ranges that are known to belong to a certain cloud provider (that is just a guess though, since we have no way of confirming that).

**Comment by kskip001** [comment]
Got it, thanks for sharing! I'll look for ways to get around this in the future.

Cheers!
