### ISSUE TITLE
How to get captions with punctuation?

### ISSUE THREAD

**Issue by Fidelalencar** [jdepoix/youtube-transcript-api#86]
The code as it currently is, cleans the punctuation from the original subtitles.
I need them with punctuation, how can I do that ?
I'm new at programming and couldn't find where the code is removing the punctuation.
I would appreciate some help.

**Comment by jdepoix** [comment]
Hi @Fidelalencar,
the code does not remove any punctuations. There simply are no punctuations in the subtitles generated by YouTube.

**Comment by Fidelalencar** [comment]
Ok, I got the point, your notes states : 
"By default this module always picks manually created transcripts over automatically created ones,"
But for some reason, the transcript being downloaded for the videos I tried were not the manually created.
For example, for this 2 videos, it downloads the "en", not the "en-GB" (which is the manually created):
a = YouTubeTranscriptApi.get_transcript("8gtSNjnjPOk")
a = YouTubeTranscriptApi.get_transcript("pvgfucVF5cU")  

![image](https://user-images.githubusercontent.com/44216783/96461418-bb7d9d80-11fa-11eb-9a3c-0ff91f4f4fe2.png)

**Comment by jdepoix** [comment]
That's because the default language is `en` not `en-GB`. Those are two different language codes. If there was a manually created `en` transcript, you'd get that one.

**Comment by hugotiburtino** [comment]
Actually, that seems to be a nice improvement, since someone interested on en would prefer to have manual transcription in en-GB than an automatic one in en.

**Comment by jdepoix** [comment]
But it could also lead to a lot of bugs because you might not get the specific language you asked for. Also this would require the module to check if the given language code is a substring of any of the available ones. So any language code which has the substring `en` could potentially match. Since there is no complete list of all available codes, the code could be anything, which means that I can't make sure that matching by substring wouldn't create false matches.
Also I prefer the default behaviour of this module to be explicit rather than implicit. The user still has the option to implement this behaviour without much effort, using `list_transcripts(...)` and then iterating over all available transcripts, while matching languages however he wants to. If however the module already does a fuzzy matching for you, you can't work around that as a user of the module. This just makes for more predictable behaviour, which I would consider to be cleaner code.
