### ISSUE TITLE
I want another kinds of sub

### ISSUE THREAD

**Issue by nguyen-d4y** [jdepoix/youtube-transcript-api#99]
I need the function changing from this language to another languages. 
Example: from en to vi
Love,
Duy.

**Comment by crhowell** [comment]
@nguyen-d4y You will want to be more descriptive about what the issue is if you submit an issue. Include details like which function you are using, what you are trying to do in your code that is broken. 🙂 

If you cant retrieve a transcript in a given language. You can try using `.translate()` to translate from a language like EN to VI. This is covered in the [Readme](https://github.com/jdepoix/youtube-transcript-api#list-available-transcripts) for this repo.

If you are doing this in a script `.py` file using the YouTubeTranscriptApi class.

```python
from youtube_transcript_api import YouTubeTranscriptApi

# Retrieve a list of possible transcripts.
transcript_list = YouTubeTranscriptApi.list_transcripts('VIDEO_ID_HERE')
transcript = transcript_list.find_generated_transcript(['en'])
# Translate from a found lang to vi
translated = transcript.translate('vi').fetch()
print(translated)
```

Is that what you are trying to get to?

**Comment by nguyen-d4y** [comment]
Thank you for so quick reflection!
